services:
  react:
    image: node
    working_dir: /workspaces/app/frontend
    volumes:
      - ..:/workspaces/app:cached
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - express

  express:
    image: node
    working_dir: /workspaces/app/backend
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=concurso

    volumes:
      - ..:/workspaces/app:cached
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concurso
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
